user_validates:
  max_leght_name: 50
  min_leght_pass: 6
  max_leght_email: 255
user_gravatar:
  size: 80
paging:
  per: 10
micropost_validates:
  max_leght_content: 150
  five: 5
img:
  height: 400
  width: 400
twomuoi: 20
